export const DI_TOKENS = {
  GameApplication: Symbol.for('GameApplication'),
  SceneRoot: Symbol.for('SceneRoot'),
  GameLoop: Symbol.for('GameLoop'),
  AssetService: Symbol.for('AssetService'),
  GameWorld: Symbol.for('GameWorld'),
  SpriteStore: Symbol.for('SpriteStore'),
  GameCommands: Symbol.for('GameCommands'),
  CameraBootstrapService: Symbol.for('CameraBootstrapService'),
  CameraCommandService: Symbol.for('CameraCommandService'),
  TweenRuntimeStore: Symbol.for('TweenRuntimeStore'),
  TweenSystem: Symbol.for('TweenSystem'),
  TweenService: Symbol.for('TweenService'),
  CameraSystem: Symbol.for('CameraSystem'),
  RenderSystem: Symbol.for('RenderSystem'),
  Systems: Symbol.for('Systems'),
  PuzzleGridService: Symbol.for('PuzzleGridService'),
  PuzzleLevelLoaderService: Symbol.for('PuzzleLevelLoaderService'),
  PuzzleFlowService: Symbol.for('PuzzleFlowService'),
  CarRenderService: Symbol.for('CarRenderService'),
  CarInputService: Symbol.for('CarInputService'),
  ParticleService: Symbol.for('ParticleService'),
  PuzzleSyncSystem: Symbol.for('PuzzleSyncSystem'),
  AudioService: Symbol.for('AudioService'),
  BackgroundRenderService: Symbol.for('BackgroundRenderService'),
} as const
